[package]
name = "realethanplayzdev/loggy"
description = "A logging library written in Luau"
liecnese = "MIT"
authors = ["RadiatedExodus (RealEthanPlayzDev) <radiatedexodus@gmail.com>"]
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
